### PR TITLE
Mount EBS volume for Amazon Linux 2

### PR DESCRIPTION
**Pull request by chrisammon3000**
## Description
Updated User Data script to mount the attached EBS volume on the `/opt` directory of the gfe-db instance. Avoids out-of--memory issues when loading data.

### CODE REVIEW

**Comment by chrisammon3000** [comment]
@pbashyal-nmdp Not sure why the previous commits keep showing up but maybe it will go away if I create a new branch off of main when this is merged.

**Comment by pbashyal-nmdp** [comment]
Yes, if you PR from a new branch off of main, the older commits won't show up.

**Review by pbashyal-nmdp — APPROVED** [review]
👍

**Comment by chrisammon3000** [comment]
This was successful in loading 3 full releases, 3540, 3550, and 3560, so the pipeline is working.

**Pull request merged**
