### PR TITLE
Update Model with accession GFE->Accession

### PR DESCRIPTION
**Pull request by pbashyal-nmdp**
- Update Model with GFE->Accession instead of IPD_Allele->Accession
- Upgrade `py-ard` to support 3130
- Fix for IMGT DB versions with 3 digits
- Add Sequence to Feature node

### CODE REVIEW

**Comment by abk7777** [comment]
Tested this in my environment by loading the full dataset for 3490 with no problems.

Node summaries:
| Label           | Count  |
| --------------- | ------ |
| `["GFE"]`       | 33446  |
| `["Submitter"]` | 1      |
| `["Sequence"]`  | 33446  |
| `["Feature"]`   | 28687  |
| `["IPD_Allele"]`| 33446  |
| `["IPD_Accession"]`| 33446  |

Relationship summaries:
| Relationship       | Count  |
| ------------------ | ------ |
| "HAS_FEATURE"      | 577924 |
| "HAS_SEQUENCE"     | 66892  |
| "SUBMITTED"        | 66892  |
| "HAS_IPD_ACCESSION"| 66892  |
| "HAS_IPD_ALLELE"   | 66892  |

**Comment by abk7777** [comment]
Had to make a small change to `docker build` to get it to work, but I will update this in a separate pull request with other changes, just leaving it here because it's good to know.
```makefile
# gfe-db/pipeline/jobs/Makefile
docker build \
	-t "$${BUILD_REPOSITORY}" \
	--platform "linux/amd64" \ # specifying the deployment platform prevents errors if you're using Apple silicon M1/M2 (these use linux/arm) 
	build/ && \
```

**Review by abk7777 — APPROVED** [review]
Looks good no issue deploying other than needing to specify the platform for Docker build since I'm using an M2 macbook

**Comment by pbashyal-nmdp** [comment]
Awesome. Thanks for the tip!

**Pull request merged**
