### PR TITLE
Add backup to S3; Configure Neo4j AMI for EC2; Configure database EBS volume; Update graph schema

### PR DESCRIPTION
**Pull request by abk7777**
This PR adds backup to S3 using Systems Manager.

Notes:
Trying to perform the backup using the Docker image was more difficult than anticipated. To remedy this the Neo4j Community Edition AMI is in place of Docker, which allows for much more visibility into the database operation.

The backup employs a maintenance window, task and target which runs a remote script stored in S3 on the database instance, performs the graph data dump and copies it to S3. The window can be set to any time period.

Additional changes made since the original PR:

1/12/22 - Configure Neo4j AMI for EC2
Changes made to EC2 user data:
- [x] Added `DataBucketName` parameter
- [x] `neo4j.template` is fetched from S3
  - [x] Confirmed that customs settings in `/etc/neo4j/neo4j.template` are in `/var/lib/neo4j/conf/neo4j.conf`
- [x] Fixed issue pushing Neo4j and Ubuntu boot logs to S3
- [x] Update default password with chosen password, avoids having to reset on first login

Notes on EC2 configuration:
The Neo4j CE AMI includes a `pre-neo4j.sh` script which runs before Neo4j starts. This script dynamically sets configuration values like JVM heap size and other settings, so these should not need to be updated. The following changes were made using `neo4j.template`:
- `dbms.security.procedures.unrestricted=apoc.*,gds.*` enabled to allow APOC and Graph Data Science plugins
- `dbms.logs.http.enabled=true` enabled to capture HTTP logs for debugging

1/12/22 - Configure database EBS volume
Adds the following:
- [x] Configuration for root EBS volume for database instance
- [x] Parameter to set the volume size on deploy

### CODE REVIEW

**Comment by abk7777** [comment]
Next steps:
- [ ] KIR
- [ ] User submitted sequences

gfe-db todo list:
- [ ] add plugins to Neo4j
- [ ] configure neo4j.conf, set default password
- [ ] capture logging from cloudformation deployments
- [ ] update makefile for administrative tasks
  - [ ] import config or cloud state to a local json
  - [ ] Manually run the pipeline with specific params using `make run release=<release version>`
  - [ ] Retrieve the Neo4j endpoint using `make get.neo4j`
- [ ] consider a restoration strategy
- [ ] add hosted zone/ssl
- [ ] Add `releases_processed`, `releases_skipped` to state JSON for more control
- [ ] Add correct error handling to the load script so that failed queries are caught

**Comment by abk7777** [comment]
Added SQS queue for failed alleles and updated schema. Also linked some old issues that are resolved by this PR.

**Review by mmaiers-nmdp — COMMENTED** [review]
Looks good to me

**Review by pbashyal-nmdp — APPROVED** [review]
👍

**Pull request merged**
